test_task:
  container:
    matrix:
      image: openjdk:8-jdk-stretch
      image: openjdk:11-jdk-stretch
  test_script: ./mvnw clean install

windows_test_task:
  windows_container:
    matrix:
      image: openjdk:8-jdk-windowsservercore-1803
      image: openjdk:11-jdk-windowsservercore-1803
    os_version: 1803
  test_script: mvnw.cmd clean install
